Sprint 7/feature/ypg 52/oauth
yandex-practicum-game/team-project-game pull request #30
Opened 2023-05-05 20:25 UTC by RafaOstrovskiy

### Добавить OAuth-авторизацию в проект

### Скриншоты/видяшка (если есть)
<img width="814" alt="image" src="https://user-images.githubusercontent.com/73179185/236548691-c551755d-0f1f-4477-873c-f740775798b6.png">
[video](https://www.youtube.com/watch?v=G8oW-UgftCU)

### TBD (если есть)

2023-05-05 20:37 UTC, Johnny-sel commented on packages/client/src/constants/apiConfig.ts
> +  REDIRECT_URI = 'http://localhost:3000',
а какое поведение будет в production ? на домене https://galaxian-game.vercel.app/ . Может сделать через process.env.NODE_ENV !== 'production' ? http://localhost:3000 : https://galaxian-game.vercel.app/. Либо подключить https://www.npmjs.com/package/config, и уже настроить переменные там для прода и дева

2023-05-05 20:43 UTC, Johnny-sel commented on packages/client/src/pages/Login/LoginPage.tsx
> +      window.open(
у нас сейчас уже ssr, проверь пожалуйста это момент, сработает ли window , если ты сделаешь сборку для сервера и запустишь через сервер (yarn build, yarn dev:server) . Если будет ошибка при обновлении страницы  LoginPage, попробуй поставить вместо window, globalThis

2023-05-05 20:44 UTC, RafaOstrovskiy commented on packages/client/src/constants/apiConfig.ts
> +  REDIRECT_URI = 'http://localhost:3000',
точно, забыл добавить

2023-05-05 20:44 UTC, Johnny-sel commented on packages/client/src/pages/StartGame/StartGame.tsx
> +    const code = new URLSearchParams(window.location.search).get('code')
тут window тоже может не сработать на ssr, лучше проверить

2023-05-05 21:53 UTC, RafaOstrovskiy commented on packages/client/src/constants/apiConfig.ts
> +  REDIRECT_URI = 'http://localhost:3000',
пофиксил

2023-05-05 21:54 UTC, RafaOstrovskiy commented on packages/client/src/pages/Login/LoginPage.tsx
> +      window.open(
работает с window

2023-05-05 21:54 UTC, RafaOstrovskiy commented on packages/client/src/pages/StartGame/StartGame.tsx
> +    const code = new URLSearchParams(window.location.search).get('code')
тоже работает

2023-05-05 22:14 UTC, Johnny-sel approved these changes

2023-05-05 23:02 UTC, IvanPeleshok commented on packages/client/src/pages/Login/LoginPage.tsx
> +      const redirectUri =
Давай блок try вынесем в rtk query
Немного погуглил, есть такое: onQueryStarted
https://redux-toolkit.js.org/rtk-query/usage/queries
https://habr.com/ru/companies/netcracker/articles/646163/

Как раз там можно будет определять redirectUri  и открывать окно

2023-05-05 23:05 UTC, IvanPeleshok commented on packages/client/src/pages/StartGame/StartGame.tsx
> +    const redirect_uri =
Встречается больше раза - можно подумать о том, чтобы вынести в переиспользуемую переменную

2023-05-05 23:06 UTC, IvanPeleshok commented on packages/client/src/pages/StartGame/StartGame.tsx
> +    await oAuthSignIn({ code, redirect_uri })
Такое ощущение, что нет необходимости получать параметры функции
Доступ к ним доступен и внутри oAuthSignIn

2023-05-06 09:29 UTC, IvanPeleshok requested changes
Есть замечания

2023-05-06 13:30 UTC, RafaOstrovskiy commented on packages/client/src/pages/StartGame/StartGame.tsx
> +    await oAuthSignIn({ code, redirect_uri })
не совсем понял, имеешь ввиду доставать code из адресной строки прямо из mutation oAuthSignIn?

2023-05-07 09:47 UTC, IvanPeleshok commented on packages/client/src/pages/StartGame/StartGame.tsx
> +    await oAuthSignIn({ code, redirect_uri })
code можно оставить здесь, т.к есть условие
Обрати внимание на наименование переменных. В данном случае redirect_uri должна иметь наименование redirectUri, поскольку **_** полагается только для константных переменных

2023-05-07 11:35 UTC, NikolosHGW approved these changes

2023-05-07 12:57 UTC, RafaOstrovskiy commented on packages/client/src/pages/Login/LoginPage.tsx
> +      const redirectUri =
спасибо за совет, поправил

2023-05-07 12:58 UTC, RafaOstrovskiy commented on packages/client/src/pages/StartGame/StartGame.tsx
> +    const redirect_uri =
вынес

2023-05-07 12:58 UTC, RafaOstrovskiy commented on packages/client/src/pages/StartGame/StartGame.tsx
> +    await oAuthSignIn({ code, redirect_uri })
поправил

2023-05-07 13:31 UTC, IvanPeleshok approved these changes

2023-05-07 13:36 UTC, merged